# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakey', '0003_auto_20180321_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='profile',
        ),
        migrations.AlterField(
            model_name='post',
            name='recipe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
